# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MNWSDKFrameTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MNWSDKFrameTest
  pod "AFNetworking"
  pod "MJExtension"
  pod 'SVProgressHUD'
  pod 'Toast-Swift'
  pod 'YYModel'
  pod 'WechatOpenSDK'
  pod 'Masonry'
  pod 'IQKeyboardManager'

end


